query GetCurrentCompany {
  currentCompany {
    id
    name
    street
    city
    state
    zipcode
    country
    maxEmployeeCount
    modules {
      id
      name
      description
      logoUrl
      price
      coursesCount
      courses {
        id
        name
        videoUrl
        sequence
      }
    }
  }
}

query GetCompanyEmployee {
  employees {
    id
    firstName
    lastName
    email
    phoneNumber
  }
}
