fragment Department on Department {
  id
  name
  courses {
    id
  }
}

query GetDepartments {
  departments {
    ...Department
  }
}

mutation CreateDepartment($name: String!) {
  createDepartment(name: $name) {
    ...Department
  }
}

mutation AssignCourse($departmentId: ID!, $courseId: ID!, $assign: Boolean!) {
  assignCourse(
    departmentId: $departmentId
    courseId: $courseId
    assign: $assign
  )
}
